version: '3.8'
services:
  teamhack_recond:
    image: innovanon/teamhack_recond
    container_name:  teamhack_recond
    ports:
      - "0.0.0.0:6000:6000/tcp"
    volumes:
      #- syslog-client:/etc/rsyslog.d:ro
      - recond:/var/teamhack/etc:ro
    restart:         always
    #network_mode:    service:vpn-s1
    #healthcheck:
    ##  test: ["CMD-SHELL", "exec 3<> /dev/tcp/0.0.0.0/3633 ; cat <&3 ; exec 3<&-"]
    #  test: ["CMD-SHELL", "nslookup hackthebox.com 0.0.0.0"]
    #  interval:      1m
    #  timeout:       3s
    #  retries:       10
    depends_on:
      import_db:
        condition: service_started
      postgres:
        condition: service_healthy
      syslog:
        condition: service_started
      teamhack_dns:
        condition: service_healthy
      teamhack_nmap:
        condition: service_started
    #networks:
    #  network:
    #    ipv4_address: 10.5.0.10

volumes:
  recond:
    external: true

